# Generated by Django 4.0.5 on 2023-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('user', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(related_name='contacts', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallets',
            field=models.ManyToManyField(related_name='wallets', to='app.wallet'),
        ),
    ]
