# Generated by Django 4.0.5 on 2023-04-07 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('beforeDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('convert', models.ManyToManyField(through='app.Conversion', to='app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('P', 'Personal Wallet'), ('S', 'Shared Wallet'), ('O', 'Organization Wallet')], max_length=1)),
                ('currency', models.ManyToManyField(through='app.Asset', to='app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transactionType', models.CharField(choices=[('bill', 'bill'), ('p2p', 'p2p'), ('topup', 'topup')], max_length=5)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency')),
                ('fromWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionFromWallet', to='app.wallet')),
                ('toWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionToWallet', to='app.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('condition', models.ManyToManyField(to='app.condition')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency')),
                ('fromWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promiseFromWallet', to='app.wallet')),
                ('toWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promiseToWallet', to='app.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='conversion',
            name='fromCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromCurrency', to='app.currency'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='toCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCurrency', to='app.currency'),
        ),
        migrations.AddField(
            model_name='condition',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency'),
        ),
        migrations.AddField(
            model_name='condition',
            name='fromWallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionFromWallet', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='condition',
            name='toWallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionToWallet', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency'),
        ),
        migrations.AddField(
            model_name='asset',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wallet'),
        ),
    ]
